#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-DateTime-Format-Builder
Version  : 0.7901
Release  : 29
URL      : https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/DateTime-Format-Builder-0.7901.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/DateTime-Format-Builder-0.7901.tar.gz
Summary  : Create DateTime parser classes and objects.
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-DateTime-Format-Builder-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(Class::Factory::Util)
BuildRequires : perl(DateTime)
BuildRequires : perl(DateTime::Format::Strptime)
BuildRequires : perl(Params::Validate)
BuildRequires : perl(Task::Weaken)

%description
DateTime::Format::Builder
Create DateTime parser classes and objects.
For installation details, see INSTALL.

%package dev
Summary: dev components for the perl-DateTime-Format-Builder package.
Group: Development
Provides: perl-DateTime-Format-Builder-devel = %{version}-%{release}
Requires: perl-DateTime-Format-Builder = %{version}-%{release}

%description dev
dev components for the perl-DateTime-Format-Builder package.


%package perl
Summary: perl components for the perl-DateTime-Format-Builder package.
Group: Default
Requires: perl-DateTime-Format-Builder = %{version}-%{release}

%description perl
perl components for the perl-DateTime-Format-Builder package.


%prep
%setup -q -n DateTime-Format-Builder-0.7901
cd %{_builddir}/DateTime-Format-Builder-0.7901

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test || :

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/DateTime::Format::Builder.3
/usr/share/man/man3/DateTime::Format::Builder::Parser.3
/usr/share/man/man3/DateTime::Format::Builder::Parser::Dispatch.3
/usr/share/man/man3/DateTime::Format::Builder::Parser::Quick.3
/usr/share/man/man3/DateTime::Format::Builder::Parser::Regex.3
/usr/share/man/man3/DateTime::Format::Builder::Parser::Strptime.3
/usr/share/man/man3/DateTime::Format::Builder::Parser::generic.3
/usr/share/man/man3/DateTime::Format::Builder::Tutorial.3

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
